### PR TITLE
fix: changed dispose to be parallel

### PR DESCRIPTION
**Pull request by daomry**
make dispose parallel, related to issue https://github.com/wixplosives/component-studio/issues/11447

### CODE REVIEW

**Comment by daomry** [comment]
see also https://github.com/wixplosives/engine/pull/1439

**Review by AviVahl — CHANGES_REQUESTED** [review]
There's a reason we do it in reversed sequential order.

We saw cases where we started A, then started B that used A, and then started C that used B. In those cases there were multiple instances where closing B before C gave us errors, as C depended on B's functionality.

For example, we created a temp directory which we wanted to delete upon dispose. If we delete that folder before closing all abstractions that used that folder (e.g. watcher), either the deletion failed (open file handles) or the abstractions that used the folder start throwing errors.

Changing this to be parallel will surely break many existing working cleanups.

**Comment by daomry** [comment]
@AviVahl I'm looking for places where cleanups fail. in the meantime, how about this new behavior to deal with them: I added an addBlocking which keep, optionally the existing behavior

**Comment by AviVahl** [comment]
We saw cleanups fail due to several reasons:
- abstraction was not cleaned at all, keeping open handles holding the process.
- abstraction was cleaned in a wrong order
- cleanup was not given enough time to cleanup

**Comment by daomry** [comment]
All tests of component-studio and engineer are passing as far as I can tell. I didn't need to add a blocking dispose anywhere...
I could use some guidance finding example of that behavior

**Pull request closed without merging**
